export const FaqView = () => {
  return (
    <>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
      <div>FaqView</div>
    </>
  );
};
