export enum CategoriesProductEnum {
  IPS_APPS = 'IPS_APPS',
  IPS_THEMES = 'IPS_THEMES',
  IPS_TRANSLATIONS = 'IPS_TRANSLATIONS',
  REACT = 'REACT',
  REACT_NATIVE = 'REACT_NATIVE',
  TYPESCRIPT = 'TYPESCRIPT',
  NODE_JS = 'NODE_JS',
  OTHERS = 'OTHERS'
}
